# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='duty',
            field=models.CharField(choices=[('\u5e97\u957f\u52a9\u7406', '\u5e97\u957f\u52a9\u7406'), ('\u5e97\u957f', '\u5e97\u957f'), ('\u90e8\u95e8\u7ecf\u7406', '\u90e8\u95e8\u7ecf\u7406'), ('\u90e8\u95e8\u603b\u76d1', '\u90e8\u95e8\u603b\u76d1'), ('\u5e02\u573a\u603b\u76d1', '\u5e02\u573a\u603b\u76d1')], default='\u5e97\u957f\u52a9\u7406\u2018\x08', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlist',
            name='sex',
            field=models.CharField(blank=True, choices=[('\u7537', '\u7537'), ('\u5973', '\u5973')], max_length=5),
        ),
    ]
