# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0002_auto_20170725_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfocollect',
            name='introduceornot',
            field=models.BooleanField(default=False),
        ),
    ]
