# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0003_auto_20170726_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfocollect',
            name='advice',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
