# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0004_studentinfocollect_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayintroduction', models.CharField(max_length=300)),
                ('datnum', models.IntegerField()),
                ('plan', models.CharField(max_length=500)),
                ('advice', models.CharField(blank=True, max_length=200)),
                ('recorderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthintroduction', models.CharField(max_length=300)),
                ('monthnum', models.IntegerField()),
                ('plan', models.CharField(max_length=500)),
                ('advice', models.CharField(blank=True, max_length=200)),
                ('recorderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonintroduction', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('startmonth', models.IntegerField()),
                ('endmonth', models.IntegerField()),
                ('plan', models.CharField(max_length=500)),
                ('advice', models.CharField(blank=True, max_length=200)),
                ('recorderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskintroduction', models.CharField(max_length=300)),
                ('completion', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('plan', models.CharField(max_length=500)),
                ('advice', models.CharField(blank=True, max_length=200)),
                ('dayid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.Day')),
                ('recorderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekintroduction', models.CharField(max_length=300)),
                ('weeknum', models.IntegerField()),
                ('plan', models.CharField(max_length=500)),
                ('advice', models.CharField(blank=True, max_length=200)),
                ('monthid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.Month')),
                ('recorderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='month',
            name='seasonid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.Season'),
        ),
        migrations.AddField(
            model_name='day',
            name='weekid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.Week'),
        ),
    ]
