# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0005_auto_20170727_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfocollect',
            name='firstfollow',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
