# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0006_auto_20170727_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfocollect',
            name='schoolclassid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
