# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0007_studentinfocollect_schoolclassid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentname', models.CharField(max_length=20)),
                ('studentid', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('campusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mms.Campus')),
                ('recorderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
