# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='problem',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
