# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0009_auto_20170727_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='datnum',
            new_name='daynum',
        ),
    ]
