# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0010_auto_20170731_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='daynum',
        ),
        migrations.RemoveField(
            model_name='month',
            name='monthnum',
        ),
        migrations.RemoveField(
            model_name='season',
            name='endmonth',
        ),
        migrations.RemoveField(
            model_name='season',
            name='startmonth',
        ),
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
        migrations.RemoveField(
            model_name='week',
            name='weeknum',
        ),
    ]
