# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0014_auto_20170731_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='weekid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mms.Week'),
        ),
    ]
