# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0016_auto_20170731_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfocollect',
            name='registornot',
            field=models.IntegerField(default=0),
        ),
    ]
