# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-01 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0017_auto_20170801_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='recordtime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 1, 14, 28, 27, 241893)),
            preserve_default=False,
        ),
    ]
