# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0018_feedback_recordtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentinfocollect',
            name='chinese',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentinfocollect',
            name='english',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentinfocollect',
            name='math',
            field=models.CharField(default='', max_length=200),
        ),
    ]
