# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0019_auto_20170814_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfocollect',
            name='infosourceintroduction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentinfocollect',
            name='visitornot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentinfocollect',
            name='wechatornot',
            field=models.IntegerField(default=0),
        ),
    ]
