# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0021_auto_20170901_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfocollect',
            name='infosource',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
