# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-10 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0023_auto_20170904_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfocollect',
            name='sex',
        ),
    ]
